feat(ci): add check to ensure upgrade version is after
Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

diff --git a/.github/workflows/create-release-pr.yml b/.github/workflows/create-release-pr.yml
--- a/.github/workflows/create-release-pr.yml
+++ b/.github/workflows/create-release-pr.yml
@@ -54,6 +54,17 @@ jobs:
         with:
           tool: cargo-edit
 
+      - name: Cache npm install
+        id: cache-node-modules
+        uses: actions/cache@v4
+        with:
+          key: node-modules-dev-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('package.json') }}
+          path: |
+            node_modules
+      - name: Install debug NPM packages
+        run: |
+          npm install -D
+
       - name: Gather project metadata
         id: project-meta
         env:
@@ -100,6 +111,14 @@ jobs:
           echo -e "next-version=$NEXT_VERSION" >> $GITHUB_OUTPUT
           echo -e "is-rust-project=$IS_RUST_PROJECT" >> $GITHUB_OUTPUT
           echo -e "is-js-project=$IS_JS_PROJECT" >> $GITHUB_OUTPUT
+
+      - name: Ensure next version is after current
+        run: |
+          IS_AFTER=$(node scripts/semver-lt.mjs ${{ steps.project-meta.outputs.current-version }} ${{ steps.project-meta.outputs.next-version }});
+          if [ "$IS_AFTER" == "false" ]; then \
+            echo "::error::project [${{ steps.project-meta.outputs.project }}] next version [${{ steps.project-meta.outputs.next-version }}] is not after current version [${{ steps.project-meta.outputs.current-version }}]";
+            exit 1;
+          fi
 
       # Set project version
       - name: Set project version
