feat(ci): improve releases (#656)
* feat(ci): improve release machinery

This commit introduces changes to improve release machinery in the
repository:

- Test artifacts post-generation during the release flow
- Update scripts to more effectively automate releases

With the merge of this commit we should be able to have essentially
one-click + one-review automated releases of any included projects.

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

* fix(ci): cliff.toml config

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

* feat(ci): add check to ensure upgrade version is after

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

* fix(ci): generated changelog

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

* fix(ci): tag-release workflow

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

* fix(ci): release packing npm

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

* feat(ci): add Rust caching

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

* refactor: enable oneshot build release

This commit updates the xtask script that performed the release build
so it can always be run immediately when building release
artifacts (in this case to help with npm prepack scripts)

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

* fix(ci): use newer version for release npm pack

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

* refactor: remove test from prepack

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

* fix(ci): test release flow

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

fix(ci): unzip of packed npm release

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

fix(ci): artifact name for jco during build

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

fix(ci): test for jco package

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

* refactor(ci): simplify package test

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

* fix(ci): test for crate & npm package

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

fix(ci): test for npm release

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

* feat(ci): add automated publish and release creation

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

* fix(ci): publish and GH release creation flow

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

* chore(ci): use pinned actions

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

* fix(ci): use tag as check for prerelease/draft

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

* fix(ci): crates release test

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

* feat(ci): update jco cli version during release

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

---------

Signed-off-by: Victor Adossi <vadossi@cosmonic.com>

diff --git a/.github/workflows/create-release-pr.yml b/.github/workflows/create-release-pr.yml
--- a/.github/workflows/create-release-pr.yml
+++ b/.github/workflows/create-release-pr.yml
@@ -54,6 +54,17 @@ jobs:
         with:
           tool: cargo-edit
 
+      - name: Cache npm install
+        id: cache-node-modules
+        uses: actions/cache@v4
+        with:
+          key: node-modules-dev-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('package.json') }}
+          path: |
+            node_modules
+      - name: Install debug NPM packages
+        run: |
+          npm install -D
+
       - name: Gather project metadata
         id: project-meta
         env:
@@ -101,6 +112,14 @@ jobs:
           echo -e "is-rust-project=$IS_RUST_PROJECT" >> $GITHUB_OUTPUT
           echo -e "is-js-project=$IS_JS_PROJECT" >> $GITHUB_OUTPUT
 
+      - name: Ensure next version is after current
+        run: |
+          IS_AFTER=$(node scripts/semver-lt.mjs ${{ steps.project-meta.outputs.current-version }} ${{ steps.project-meta.outputs.next-version }});
+          if [ "$IS_AFTER" == "false" ]; then \
+            echo "::error::project [${{ steps.project-meta.outputs.project }}] next version [${{ steps.project-meta.outputs.next-version }}] is not after current version [${{ steps.project-meta.outputs.current-version }}]";
+            exit 1;
+          fi
+
       # Set project version
       - name: Set project version
         working-directory: ${{ steps.project-meta.outputs.project-dir }}
@@ -110,6 +129,10 @@ jobs:
             cargo set-version -p ${{ steps.project-meta.outputs.project }} ${{ steps.project-meta.outputs.next-version }};
           elif [ "true" == "${{ steps.project-meta.outputs.is-js-project }}" ]; then
             npm pkg set version=${{ steps.project-meta.outputs.next-version }};
+          fi
+
+          if [ "jco" == "${{ steps.project-meta.outputs.project }}" ]; then
+            sed -i "s/version('${{ steps.project-meta.current-version }}')/version('${{ steps.project-meta.next-version }}')/" src/jco.js
           fi
 
       # Generate changelog
