feat(ci): check jco transpile size before release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -370,6 +370,23 @@ jobs:
         with:
           version: 11
 
+      # NOTE: jco-transpile packed should be ~2.1MB
+      - name: Test jco-transpile package size
+        if: ${{ needs.meta.outputs.project == 'jco-transpile' }}
+        shell: bash
+        env:
+          ARTIFACT_NAME: ${{ needs.meta.outputs.artifact-name }}
+          GH_WORKSPACE: ${{ github.workspace }}
+        run: |
+          export FILE="$GH_WORKSPACE/gh-artifacts/$ARTIFACT_NAME";
+          SIZE=$(wc -c < "$FILE");
+          MAX_SIZE=$((3 * 1024 * 1024));
+          echo -e "::info:: jco-transpile package size ${SIZE} bytes;
+          if (( SIZE > MAX_SIZE )); then
+              echo "::error:: next jco-transpile NPM package artifacts should less than 3MB";
+              exit 1;
+          fi
+
       - name: Test built jco NPM package
         if: ${{ needs.meta.outputs.project == 'jco' }}
         shell: bash
